### ISSUE TITLE
incorrect aspect ratio

### ISSUE THREAD

**Issue by v00d00m4n** [ShizCalev/MGSHDFix#13]
Game assumes aspect ratio by reading highest available resolution for desktop instead of using curently selected resolution in game as source for aspect ration or primary resolution as source or current desktop resolution.

This leads to incorrect scalling issues.

Many 4k tvs and displays has resolution 4096x2160 supported which is 17:9 but should be scalled to 16:9 by tv. Primary resolution is 16;9 - 3840x2160. Game wronly assumes 4096x2160 resolution as source of aspect ratio, and 17/9=1.8888.

When all kinds of resolution selected, lets say 16:9 game thinks that it needs to be corrected and that its actually 1.88888 instead of 1.77777. And so it vertically stretching ABSOLUTELY EVERY GAME IN MASTER collection and add vertical pillar boxes.

I think this can be fixed by preventing game from reading maximum available resolution and only allowing it to consider currently selected resolution as maximum one. So some sort of enumerated resolutions list filtering needs to be done before giving this data to games.

**Comment by Lyall** [comment]
Are you sure this is still wrong? A fix for this was added in v0.6. Can you post your `MGSHDFix.log` file?
