### ISSUE TITLE
Fix for MGS1, MG1&2 and BONUS

### ISSUE THREAD

**Issue by v00d00m4n** [ShizCalev/MGSHDFix#14]
Please let your fix work with them too, they all lacking resolution selection, all has same aspect ratio problems. And in case of MGS1 its possible to swap some values in memory to change internal rendering resolution of PS1 emulator (and hopefull other settings like bilinear filtering of textures) to actually make less ugly.  I suggest to mimic Duckstation resolution list, indlucing 2x. 4x, 8x, 9x, auto. Not sure which emulator they used but i believe it may also has some values for overscan zoom in crop or smart black bar detection to fix NTSC versions black bars.

**Comment by knight-ki11er** [comment]
>And in case of MGS1 its possible to swap some values in memory to change internal rendering resolution of PS1 emulator 
What values?

**Comment by roflcopter777** [comment]
I like hope the OP mentions MGS1 can be fixed, but is too damn lazy to actually provide said values. Great going, OP, no really.

**Comment by v00d00m4n** [comment]
> I like hope the OP mentions MGS1 can be fixed, but is too damn lazy to actually provide said values. Great going, OP, no really.

Are you mad? Why should i provide values that i dont have? I know its easy to find them with any debuger, even cheat engine, but i dont have time for that. Man who does this fix probably do have time to mess with debuger and search for values.

Game is PS1 rom inside emulator, pal (EU) and ntsc (US\JP) versions uses internal resolutions of 320x224 and 320x240, so they are easy to find and replace.

**Comment by v00d00m4n** [comment]
> > Man who does this fix probably do have time to mess with debuger and search for values.
> 
> Why do you feel entitled to other people's time? Your post and response just come as condescending. Probably not the best way to go about asking someone to do something for you, for free.

Why are do you feel yourself so smart and entitled when you ask such a stupid questions?

This is forum for reporting issues and posting ideas and suggestions for software creators.

Thats what i did , i reported issue and suggested idea. And its up to author of software what do with it. 

And i am not developer of this software for someone to demand some offsets from me and calling me lazy for suggesting ideas to author instead of doing everything myself.

If i had time for that i would not be here reporting and suggesting and would make my own fix, and probably everyone else by logic of such commenters should not ask anyone who already did something - to add some improvements, and instead should go make his own version of same thing - this is insane and stupid!).

And i answered to those insane and stupid demands from previous commenter. Nobody asked you to comment on that

Its not forums for personal opinions on someone's reports and suggestions. So you both can STFU and GTFO if you have nothing valuable to say on subject and nothing to report and nothing to suggest to author of this software.

@Lyall  can you please delete those nonsense comments from Cassian and roflcopter (and my answers to them as well) to keep issue tracking clean?

**Comment by ShizCalev** [comment]
> And in case of MGS1 its possible to swap some values in memory to change internal rendering resolution of PS1 emulator 

The way you phrased this, ie "it's possible." vs "is it possible?", implied that you KNEW that there's memory values that can be swapped to do that, which is why they were asking for you to clarify on which values you were referring to. The way it was written up was presented as a statement, not a question.

**Comment by v00d00m4n** [comment]
> > And in case of MGS1 its possible to swap some values in memory to change internal rendering resolution of PS1 emulator
> 
> The way you phrased this, ie "it's possible." vs "is it possible?", implied that you KNEW that there's memory values that can be swapped to do that, which is why they were asking for you to clarify on which values you were referring to. The way it was written up was presented as a statement, not a question.

It is a statement, i know that such values exist, because they always exist in every game in every emulator! Any value any games uses is stored in process memory, and resolution of screen used in game is also a value that always exist and sits at some offset waiting for someone to find it and change it.

This whole fix based on this principle - that value of screen resolution is always exist in process memory and can be found and swapped to change resolution! And hell lof of other fixes, patches and mods (including a couple i made for other game a while ago) for games did that before! 

I know that MGS1 emulator has value for internal resolution, author of this fix knows how to find resolutions and change them, but for some reason he did not do it with MGS1, so probably he did not think of that or forgot about it, so i guided him in this direction, we both know its possible and its a conversation between us, and comments here is not place to attack me or write your personal opinions on who is lazy or not, its only for bug reports and suggestions! Has nothing to report and suggest? Move along!

Why would i ask like an idiot "if this possible" if i know its possible and pretty easy to do and if this whole fix here is a prove that its possible? I mead dudes, what are we even discussing here? Can you stop this already and not comment anything anymore about that and stop ashaming yourself and crapping into issue tracker? 

I already told before its not the place for your personal opinions! Move along if you dont know what you talking about and has nothing to suggest or report! Nobody needs your dumb personal attacks here, guys.  

Its not my fault that some people so stupid, they always needs to comment on something they barely know anything about and so stupid that they need to start attacking someone, because of attackers own inability to understand subject of discussion! Best strategy in case if you dont know something, not comment anything and move along!

I swear - anyone who will continue this discussion and will not post anything that is report related to subject or  suggestion related to subject - will prove he is complete and talal imbecile. So stop now!

Hope that when Lyall will see the mess you guys did in this thread, he will clean all "personal" comments.

**Comment by v00d00m4n** [comment]
I found that MGS1 uses M2's emulation framework. A little history https://arstechnica.com/gaming/2019/05/required-gamer-viewing-the-history-of-m2s-japanese-retro-port-empire/

i found tool to unpack m files and messed up with scripts a little, it seems to be possible to set up resolution this way, but it did not work yet, coud be that extra settings disable in game code and even enabling them via scripts may not have effect. But its a promising start.

**Comment by Lyall** [comment]
https://github.com/nuggslet/MGSM2Fix
