### ISSUE TITLE
Game registers keyboard input in windowed mode despite losing focus.

### ISSUE THREAD

**Issue by Lyall** [ShizCalev/MGSHDFix#16]
Looks like MG1/2, MGS2 and MGS3 all have this same issue of registering keyboard inputs when using windowed mode and alt tabbing out.

**Comment by MajorZero69** [comment]
I like this bug. If you choose to fix it, I would hope you'd add the ability to toggle it as a feature, as well as control the game with dinput controllers while the game is not focused.

**Comment by Lyall** [comment]
Closing this and referring to #27 as the main issue.
