### ISSUE TITLE
Camera sensitivity increase for MGS3?

### ISSUE THREAD

**Issue by RIKLAVIEGASINTRODUCTION** [ShizCalev/MGSHDFix#3]
Not sure if this beyond the scope of this project but It'd be great if a hack for upping sensitivity in MGS3 could be implemented for KB+M. Currently it's abysmal and messing around with DPI & Mouse settings on windows is a pain.

**Comment by Lyall** [comment]
There are a few calls to windows to get the cursor position. It might be possible to hook in to it and modify the reported position thereby increasing the perceived mouse sensitivity. I'll take a look at it further tomorrow.

**Comment by Lyall** [comment]
I've added this option to the latest release (v0.7). Just need to tweak `MGSHDFix.ini` to enable it and adjust. If you can, give it a try and let me know if this works for you.

**Comment by vini1264** [comment]
I enabled the mouse sensitivity multiplier and camera speed is still slow, no matter what value I put on the multiplier

**Comment by Lyall** [comment]
> I enabled the mouse sensitivity multiplier and camera speed is still slow, no matter what value I put on the multiplier
> 
> Edit: alright, It works but I have to alt-tab the game first in order to make the multiplier setting work

I was able to replicate this on my end so I've tried altering the position of the hook. I've also added a separate X and Y multiplier. Can you try out this test build?

[MGSHDFix_v_0_7_mousetest.zip](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)

**Comment by vini1264** [comment]
> > I enabled the mouse sensitivity multiplier and camera speed is still slow, no matter what value I put on the multiplier
> > Edit: alright, It works but I have to alt-tab the game first in order to make the multiplier setting work
> 
> I was able to replicate this on my end so I've tried altering the position of the hook. I've also added a separate X and Y multiplier. Can you try out this test build?
> 
> [MGSHDFix_v_0_7_mousetest.zip](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)

Just tested it and the multiplier is now working as expected

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
Works great. Thanks.

**Comment by abdelkrim115** [comment]
> Works great. Thanks.
I modified it like this and it didn't work for me
Enabled = true
Multiplier = 10

**Comment by abdelkrim115** [comment]
> > > I enabled the mouse sensitivity multiplier and camera speed is still slow, no matter what value I put on the multiplier
> > > Edit: alright, It works but I have to alt-tab the game first in order to make the multiplier setting work
> > 
> > 
> > I was able to replicate this on my end so I've tried altering the position of the hook. I've also added a separate X and Y multiplier. Can you try out this test build?
> > [MGSHDFix_v_0_7_mousetest.zip](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)
> 
> Just tested it and the multiplier is now working as expected

I modified it like this and it didn't work for me
Enabled = true
Multiplier = 10

**Comment by ShizCalev** [comment]
Fixing broken issues, ignore this message.
