### ISSUE TITLE
Red bars on prerendered cutscenes at 4k in MGS3

### ISSUE THREAD

**Issue by theraineydaze** [ShizCalev/MGSHDFix#6]
My monitor is 3840x2160 and when I change it to that resolution in the ini I get permanent black bars on each side of the screen and the entire image in squished horizontally. 
However if I set the ini to 4096x2160 everything looks pixel perfect in a 16:9 aspect ratio. Except for any prerendered cutscene. These now show bright red bars on the side of the screen that are oldy asymmetrical.

https://i.imgur.com/xlceSbQ.jpeg

**Comment by theraineydaze** [comment]
Switching back to 3840x2160 and installing this fixed it for me:

https://steamcommunity.com/sharedfiles/filedetails/?id=3059974819

I did have to remove the xinput 1_3.dll that was included to get it working however.

**Comment by theraineydaze** [comment]
Applying the same process to MGS2 does not work the same way, the closest I can get to fixing it is by using the 4096 trick, and those same asymmetrical bars show up on prerendered cutscenes however they are black instead of red, which is way less distracting to be fair.

https://i.imgur.com/svTVeq7.jpg

**Comment by Lyall** [comment]
This is related to issue #2. Should be able to fix it in the next build by using the fixes emoose provided.

**Comment by Lyall** [comment]
Can you try out this [test build of v0.6](https://github.com/Lyall/MGSHDFix/files/13184401/MGSHDFix_v_0_6_test.zip)? It includes the framebuffer fixes that emoose provided so should possibly address your issue.

**Comment by theraineydaze** [comment]
> Can you try out this [test build of v0.6](https://github.com/Lyall/MGSHDFix/files/13184401/MGSHDFix_v_0_6_test.zip)? It includes the framebuffer fixes that emoose provided so should possibly address your issue.

Worked flawlessly with resolution set at 0. Thanks so much!
